/* Shared domain rules plus a local, non-generative fallback for the OpenAI assistant. */
globalThis.Hub = (() => {
 const fields = [ ['context','Контекст','Что происходит сейчас? Как решаете задачу сегодня?'], ['need','Потребность','Что необходимо изменить и почему это важно?'], ['users','Пользователи','Кто будет пользоваться решением? Опишите их рабочий сценарий.'], ['data','Данные и материалы','Какие данные, примеры или источники доступны команде?'], ['constraints','Ограничения','Какие сроки, технологии и ограничения доступа нужно учесть?'], ['result','Ожидаемый результат','Что команда должна передать: прототип, сервис или исследование?'], ['success','Критерии успеха','По каким измеримым показателям вы примете результат?'], ['contact','Контакт','Как команда может связаться с представителем бизнеса?'], ['interaction','Формат взаимодействия','Как часто возможны консультации и как будет предоставляться обратная связь?'] ];
 const groups = [{label:'Контекст и потребность',keys:['context','need'],weight:20},{label:'Данные и материалы',keys:['data'],weight:20},{label:'Ожидаемый результат',keys:['result'],weight:15},{label:'Критерии успеха',keys:['success'],weight:15},{label:'Ограничения',keys:['constraints'],weight:10},{label:'Пользователи',keys:['users'],weight:10},{label:'Связь с бизнесом',keys:['contact','interaction'],weight:10}];
 const present = v => typeof v === 'string' && v.trim().length > 0;
 function breakdown(task, preview=false) {return groups.map(g=>({...g,points:g.keys.every(k=>present(task[k]) && (preview || task.confirmed?.includes(k)))?g.weight:0}));}
 const score = (t,p=false)=>breakdown(t,p).reduce((n,g)=>n+g.points,0);
 const level = s => s>=90?'Приоритетная':s>=70?'Готовая':s>=40?'Рабочая':'Черновик';
 const prompt = 'Ты помощник AI Sana. Вход: {draft, topic, fields}. Сначала учти все уже сообщённые факты. Задай ровно 3 коротких открытых и нейтральных вопроса по самым важным пробелам. Не предлагай варианты ответов, не подсказывай желаемое решение, не повторяй уже заполненные поля и не выдумывай факты. Если задача подробно описана, уточни проверку результата, пользователей или ограничения, а не пересказывай черновик. Верни JSON {questions:[{field,question}]}. Допустимые field: '+fields.map(f=>f[0]).join(', ')+'. Ответы пользователя переносятся дословно и подтверждаются человеком.';
 const questionSets={Образование:{need:'На каком этапе обучения или поступления возникает затруднение?',users:'Кто будет пользоваться решением и в какой ситуации?',data:'Какие учебные материалы доступны и кто подтвердит их актуальность?',constraints:'Какие правила конфиденциальности, сроки или ограничения доступа нужно учесть?',result:'Какой результат команда должна передать для проверки?',success:'На каких вопросах или сценариях вы проверите качество решения?',contact:'Кто со стороны организации будет проверять результат?',interaction:'Как команде задавать вопросы и как часто получать обратную связь?'},Ритейл:{need:'В каких товарах или периодах проблема заметнее всего?',users:'Кто будет использовать результат в ежедневной работе?',data:'Какие данные о продажах и остатках доступны и за какой период?',constraints:'Какие сроки поставки или правила учёта нужно соблюдать?',result:'Какой формат результата удобно использовать в работе?',success:'С каким периодом и показателем вы сравните результат?',contact:'Кто будет проверять рекомендации со стороны магазина?',interaction:'Как часто команда сможет сверять результат с сотрудниками?'},Логистика:{need:'На каком этапе доставки чаще возникает проблема?',users:'Кто будет использовать результат и какое решение он принимает?',data:'Какие обезличенные сведения о доставках или отзывах доступны?',constraints:'Какие правила приватности и сроки обработки нужно соблюдать?',result:'Какой результат поможет сотрудникам проверить гипотезу?',success:'На какой выборке и показателе вы оцените качество?',contact:'Кто сможет проверить правильность категорий или выводов?',interaction:'Как команда будет согласовывать спорные случаи?'},Агротех:{need:'На каких участках или в какие периоды проблема заметнее?',users:'Кто будет использовать рекомендации на участке?',data:'Какие показания и периоды измерений доступны команде?',constraints:'Какие сезонные, технические или безопасностные ограничения важны?',result:'Как должен выглядеть проверяемый результат для участка?',success:'По каким измерениям вы поймёте, что рекомендация полезна?',contact:'Кто сможет сверять рекомендации с практикой?',interaction:'Когда команда сможет обсуждать наблюдения с агрономом?'},Промышленность:{need:'Какие заявки или этапы процесса чаще задерживаются?',users:'Кто создаёт заявки и кто назначает исполнителя?',data:'Какие обезличенные примеры заявок и статусов можно использовать?',constraints:'Какие правила безопасности, доступа и сроки нужно учесть?',result:'Какой сценарий должен работать в прототипе?',success:'На каком наборе случаев вы проверите результат?',contact:'Кто будет владельцем процесса и проверит демонстрацию?',interaction:'Как команда сможет уточнять сценарии у сотрудников?'}};
 const priorities={Образование:['users','data','success','constraints','result','interaction','contact','need'],Ритейл:['data','users','success','constraints','result','need','interaction','contact'],Логистика:['data','users','success','constraints','result','need','interaction','contact'],Агротех:['data','users','constraints','success','result','need','interaction','contact'],Промышленность:['users','data','constraints','result','success','need','interaction','contact']};
 const cues={need:/хотим|нужно|проблем|теря|сниж|сократ|опоздан|списан|не хватает/i,users:/студент|абитуриент|сотрудник|менеджер|клиент|пользовател|оператор|мастер|фермер|родител|покупател/i,data:/данн|таблиц|csv|выгруз|faq|материал|датчик|показани|источник|отзыв|продаж/i,constraints:/срок|недел|огранич|без персональн|не переда|доступ|только на основе/i,result:/прототип|дашборд|веб-помощник|веб-форма|панел|интерфейс|каталог|карта|классификатор/i,success:/не менее|не больше|ошибка|точност|процент|%|контрольн|выборк/i,contact:/@[\w.-]+|контакт|связаться/i,interaction:/консультац|встреч|обратн\w* связ|еженедел|кажд\w* (?:недел|день)|разбор/i};
 const followups={need:'Что в текущем процессе важнее всего изменить?',users:'Кто из упомянутых пользователей будет основным и в каком сценарии?',data:'Какие именно из упомянутых данных можно передать команде и в каком формате?',constraints:'Какие ограничения по доступу, срокам или приватности действуют для этих материалов?',result:'Как команда сможет показать результат на описанном сценарии?',success:'На какой контрольной выборке и каким показателем проверить результат?',contact:'Кто сможет подтвердить исходные факты и результат?',interaction:'Когда и как удобно сверять промежуточный результат?'};
 function localAssistant(task) {const source=`${task.draft||''} ${task.context||''}`,priority=priorities[task.topic]||['need','users','data','constraints','result','success','contact','interaction'],missing=priority.filter(key=>!present(task[key])),selected=[...missing,...priority.filter(key=>present(task[key]))].slice(0,3),set=questionSets[task.topic]||{};return {questions:selected.map(key=>({field:key,question:cues[key]?.test(source)?followups[key]:set[key]||fields.find(([name])=>name===key)?.[1]+'?'}))};}
 function validateAssistant(raw) {const obj=typeof raw==='string'?JSON.parse(raw):raw;if(!obj || !Array.isArray(obj.questions)||obj.questions.length<3||obj.questions.length>5)throw Error('Некорректный формат ответа помощника');const seen=new Set(),leading=/(?:^|\s)(?:не так ли|верно ли|правильно ли|не лучше ли|вам ведь|не хотите ли|подходит ли вам|например[:,])/iu;for(const q of obj.questions){if(!q||!fields.some(f=>f[0]===q.field)||!present(q.question)||q.question.length>700||seen.has(q.field)||leading.test(q.question))throw Error('Некорректный или наводящий вопрос');seen.add(q.field);}return obj;}
 function assistant(task, raw) {try{return { ...validateAssistant(raw===undefined?localAssistant(task):raw),fallback:false};}catch{return {...localAssistant(task),fallback:true};}}
 function confirm(t) {return {...t,confirmed:fields.filter(f=>present(t[f[0]])).map(f=>f[0])};}
 function safeUrl(s){try {const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}}
 function approveProgress(p,evidence){if(p.status!=='selected'||p.completed||!present(evidence))throw Error('Этап недоступен для подтверждения');return {...p,completed:true,evidence:evidence.trim(),points:50};}
 function filterTasks(tasks, filters={}, favorites=[]) {
  const normalize=value=>String(value??'').toLocaleLowerCase('ru').replace(/ё/g,'е');
  const words=normalize(filters.search).trim().split(/\s+/).filter(Boolean);
  return tasks.filter(t=>t.published && (!filters.topic||t.topic===filters.topic) && (!filters.level||level(score(t))===filters.level) && (!filters.onlyFavorites||favorites.includes(t.id)) && words.every(word=>normalize([t.title,t.company,t.topic,t.context,t.need,t.result,t.users,t.data].join(' ')).includes(word))).sort((a,b)=>score(b)-score(a)||b.created-a.created);
 }
 const matchGroups=[{skills:/nlp|язык|текст|коммуникац/i,task:/вопрос|faq|отзыв|текст|язык|обращени|помощник|поиск/i,label:'обработка текста'},{skills:/аналитик|ml|python|pandas|data/i,task:/данн|прогноз|спрос|продаж|таблиц|csv|датчик|метрик|остатк/i,label:'аналитика и данные'},{skills:/frontend|ux|ui|дизайн|react|vue|javascript|figma/i,task:/интерфейс|веб|панел|дашборд|карта|каталог|форма|экран/i,label:'веб-интерфейс'},{skills:/backend|fullstack|node|postgres|баз|api|сервер/i,task:/интеграц|база|статус|заявк|хранен|сервис|данн/i,label:'сервисная разработка'}];
 function match(task,team) {if(!task||!team)return {score:0,reasons:[]};const topicMatch=(team.interests||[]).includes(task.topic),text=[task.title,task.context,task.need,task.users,task.data,task.constraints,task.result,task.draft].join(' '),profile=[...(team.skills||[]),...(team.tech||[])].join(' '),hits=matchGroups.filter(g=>g.skills.test(profile)&&g.task.test(text)),score=Math.min(100,(topicMatch?55:0)+hits.length*15),reasons=[];if(topicMatch)reasons.push(`тема «${task.topic}» входит в интересы команды`);hits.slice(0,2).forEach(g=>reasons.push(`подходят навыки: ${g.label}`));if(!reasons.length)reasons.push('совпадение по теме и навыкам невысокое; карточку стоит проверить вручную');return {score,reasons};}
 return {fields,groups,score,breakdown,level,prompt,assistant,validateAssistant,confirm,safeUrl,approveProgress,filterTasks,match};
})();
