/* Shared, dependency-free domain logic. Local assistant is an explicit API stub. */
globalThis.Hub = (() => {
 const fields = [ ['context','Контекст','Что происходит сейчас? Как решаете задачу сегодня?'], ['need','Потребность','Что необходимо изменить и почему это важно?'], ['users','Пользователи','Кто будет пользоваться решением? Опишите их рабочий сценарий.'], ['data','Данные и материалы','Какие данные, примеры или источники доступны команде?'], ['constraints','Ограничения','Какие сроки, технологии и ограничения доступа нужно учесть?'], ['result','Ожидаемый результат','Что команда должна передать: прототип, сервис или исследование?'], ['success','Критерии успеха','По каким измеримым показателям вы примете результат?'], ['contact','Контакт','Как команда может связаться с представителем бизнеса?'], ['interaction','Формат взаимодействия','Как часто возможны консультации и как будет предоставляться обратная связь?'] ];
 const groups = [{label:'Контекст и потребность',keys:['context','need'],weight:20},{label:'Данные и материалы',keys:['data'],weight:20},{label:'Ожидаемый результат',keys:['result'],weight:15},{label:'Критерии успеха',keys:['success'],weight:15},{label:'Ограничения',keys:['constraints'],weight:10},{label:'Пользователи',keys:['users'],weight:10},{label:'Связь с бизнесом',keys:['contact','interaction'],weight:10}];
 const present = v => typeof v === 'string' && v.trim().length > 0;
 function breakdown(task, preview=false) {return groups.map(g=>({...g,points:g.keys.every(k=>present(task[k]) && (preview || task.confirmed?.includes(k)))?g.weight:0}));}
 const score = (t,p=false)=>breakdown(t,p).reduce((n,g)=>n+g.points,0);
 const level = s => s>=90?'Приоритетная':s>=70?'Готовая':s>=40?'Рабочая':'Черновик';
 const prompt = 'Ты помощник AI Sana. Вход: {draft, topic, fields}. Найди недостающие сведения и задай минимум 3 уместных вопроса. Верни JSON {questions:[{field,question}]}. Допустимые field: '+fields.map(f=>f[0]).join(', ')+'. Не добавляй факты, не назначай команды. Вопросы только о задаче. Ответы пользователя переносятся дословно и подтверждаются человеком.';
 function localAssistant(task) {const missing=fields.filter(f=>!present(task[f[0]]));const selected=[...missing,...fields.filter(f=>present(task[f[0]]))].slice(0,Math.max(3,missing.length));return {questions:selected.map(([field,,question])=>({field,question:question+(field==='data'?' Для темы «'+task.topic+'» укажите также условия доступа.':'')}))};}
 function validateAssistant(raw) {const obj=typeof raw==='string'?JSON.parse(raw):raw;if(!obj || !Array.isArray(obj.questions)||obj.questions.length<3||obj.questions.length>12)throw Error('Некорректный формат ответа помощника');const seen=new Set();for(const q of obj.questions){if(!q||!fields.some(f=>f[0]===q.field)||!present(q.question)||q.question.length>700||seen.has(q.field))throw Error('Некорректный вопрос');seen.add(q.field);}return obj;}
 function assistant(task, raw) {try{return { ...validateAssistant(raw===undefined?localAssistant(task):raw),fallback:false};}catch{return {...localAssistant(task),fallback:true};}}
 function confirm(t) {return {...t,confirmed:fields.filter(f=>present(t[f[0]])).map(f=>f[0])};}
 function safeUrl(s){try {const u=new URL(s);return ['http:','https:'].includes(u.protocol)?u.href:null;}catch{return null;}}
 function approveProgress(p,evidence){if(p.status!=='selected'||p.completed||!present(evidence))throw Error('Этап недоступен для подтверждения');return {...p,completed:true,evidence:evidence.trim(),points:50};}
 return {fields,groups,score,breakdown,level,prompt,assistant,validateAssistant,confirm,safeUrl,approveProgress};
})();
